### PR TITLE
add maybeReader

### PR DESCRIPTION
**Pull request by nhibberd**

### CODE REVIEW

**Comment by jystic** [comment]
👍 on 🍏

**Comment by tranma** [comment]
this should have been in optparse itself 👍

**Comment by thumphries** [comment]
🍔 i write this every time i use optparse

**Comment by nhibberd** [comment]
Wondering if we add a version of `eitherReader` which is on `Text` on `String`

**Comment by thumphries** [comment]
> Wondering if we add a version of eitherReader which is on Text not on String

would use

**Comment by markhibberd** [comment]
:100:

**Comment by HuwCampbell** [comment]
Thinking of adding a maybeReader to optparse 0.13. For the text version, maybe call it something else so it doesn't clash?

**Pull request merged**
