### PR TITLE
Upgrade mafia + pin clock to 0.5.x

### PR DESCRIPTION
**Pull request by jystic**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
:santa: once it actually builds cleanly.

**Comment by jystic** [comment]
Weird that it's not, I wonder if master even builds?

**Comment by jystic** [comment]
Yeah looks like master doesn't build at the moment :(

https://ci.ambiata.com/job/x/55/console

**Comment by jystic** [comment]
for reference: https://github.com/corsis/clock/issues/35

**Pull request merged**
