### PR TITLE
x-vector: correct lower bound for vector

### PR DESCRIPTION
**Pull request by olorin**
Data.Vector.Fusion.Bundle was introduced in vector-0.11.0.0.

! @jystic

### CODE REVIEW

**Comment by jystic** [comment]
I worry that many of our projects still have `0.10.*` bounds for vector, but I suspect this isn't as easy as using CPP on the stuff that uses `Data.Vector.Fusion.Bundle`?

I think x- projects should be maximally compatible, but I think that ship has already sailed here.

**Comment by olorin** [comment]
> I worry that many of our projects still have 0.10.* bounds for vector, but I suspect this isn't as easy as using CPP on the stuff that uses Data.Vector.Fusion.Bundle?

That is a valid concern; I'll look into whether it can be wrangled into compatibility.

**Comment by jystic** [comment]
> That is a valid concern; I'll look into whether it can be wrangled into compatibility.

If not, I'm happy to 👍, this was already broken, so we're just being truthful about it now. If it's possible to keep compatible without too much hassle that would be great though.

**Comment by olorin** [comment]
Haven't had time to look at this, will merge as-is for now.

**Pull request merged**
