### PR TITLE
Add sepByByteBounded for bytestring conduits

### PR DESCRIPTION
**Pull request by olorin**
/cc @nhibberd

### CODE REVIEW

**Comment by markhibberd** [comment]
This is basically to implement linesBounded on bytestring is it?

**Comment by markhibberd** [comment]
:+1:

**Comment by olorin** [comment]
> This is basically to implement linesBounded on bytestring is it?

Yep, intend to use it for warden, and @nhibberd mentioned he had a use for it as well.

**Comment by domdere** [comment]
Are there any multibyte unicode points that contain newline chars? or is there something in the unicode spec that forbids new unicode points from containing newline chars?

**Comment by markhibberd** [comment]
@domdere 
> Are there any multibyte unicode points that contain newline chars? or is there something in the unicode spec that forbids new unicode points from containing newline chars?

The wonders of utf8, for ascii sub-set you are always know you are looking at a byte that is a valid char, not some subsequence of a larger multi-byte char, as the leading bits tell you where you are in the sequence.

```
Char sequences ---

  7	U+0000           U+007F	        1	0xxxxxxx
11	U+0080           U+07FF	        2	110xxxxx	10xxxxxx
16	U+0800           U+FFFF	        3	1110xxxx	10xxxxxx	10xxxxxx
21	U+10000          U+1FFFFF       4	11110xxx	10xxxxxx	10xxxxxx	10xxxxxx
26	U+200000         U+3FFFFFF      5	111110xx	10xxxxxx	10xxxxxx	10xxxxxx	10xxxxxx
31	U+4000000        U+7FFFFFFF     6	1111110x	10xxxxxx	10xxxxxx	10xxxxxx	10xxxxxx	10xxxxxx
```

**Comment by domdere** [comment]
Whoa cool that's pretty awesome, is that a guarantee we can make for all
the common encodings?

**Comment by olorin** [comment]
@domdere works for \n in latin-1 at least, not sure about the others.

**Comment by domdere** [comment]
> works for \n in latin-1 at least, not sure about the others

:+1:

**Pull request merged**
