### PR TITLE
Update to shiny new optsparse-applicative

### PR DESCRIPTION
**Pull request by jystic**
ping @HuwCampbell @nhibberd

### CODE REVIEW

**Comment by HuwCampbell** [comment]
We might want to edit the default behaviour a little. With no text, we'll now get the Missing: information as well as the help text.

**Comment by jystic** [comment]
Ok, do you want to do that? I'm not really sure what needs to be done

I can close this PR and wait for the proper solution

**Comment by tranma** [comment]
I guess this is the whole reason we'd want to update optparse (ever):
`* Allow multiple short flags to be concatenated together behind a single hyphen, e.g. "-xcf".`

**Comment by nhibberd** [comment]
Im more interested in the missing argument one :hurtrealbad:

**Comment by jystic** [comment]
yeah i'm keen for what @tranma said

**Comment by HuwCampbell** [comment]
Ok

**Comment by tranma** [comment]
mergerised? :rocket:

**Comment by nhibberd** [comment]
:rocket:

**Pull request merged**
