### PR TITLE
Import htoml-0.1.0.3 in to x-htoml

### PR DESCRIPTION
**Pull request by jystic**
As discussed, this pulls `htoml-0.1.0.3` in to `x-htoml`, removing the test suites and the `vector` / `aeson` dependencies.

! @markhibberd @nhibberd 
/jury approved @nhibberd

### CODE REVIEW

**Comment by nhibberd** [comment]
:+1: 

Lock file need upgrading at all? Probably worth adding a note for about upgrading this even in the PR description

**Comment by jystic** [comment]
The reason for doing this is because `htoml-0.1.0.3` on hackage has a `Cabal` dependency which is causing us a bunch of problems.

If your build is broken because you updated `x`, all you need to do is remove your dependency on `htoml` and make sure you have a dependency on `x-htoml`.

**Comment by markhibberd** [comment]
This needs a copy of the original license and a COPYING note with respect to the fork. It should be clear that it is htoml code. 👍 after that.

**Comment by jystic** [comment]
So original license in `LICENSE` and a file called `COPYING` which explains that it is a fork? Or the whole lot inside `COPYING`?

**Comment by markhibberd** [comment]
I would have a `LICENSE.htoml` and a COPYING, that says why and what is going on.

**Pull request merged**
