### PR TITLE
Added a method to transform a parsing function to a Parser

### PR DESCRIPTION
**Pull request by etorreborre**
@tmcgilchrist this can be useful but it's hard to find a good name for this function.

### CODE REVIEW

**Comment by domdere** [comment]
:+1: but i think `eitherText` is sufficient as a name

**Comment by domdere** [comment]
really surprised this doesnt exist in `attoparsec` already actually, tried looking but couldnt find it

**Comment by charleso** [comment]
Out of curiosity, where are you going to use this?

**Comment by charleso** [comment]
Can we revert this?

**Comment by domdere** [comment]
yeah i agree with @charleso 

the ramifications of `takeText` didnt occur to me >_<

**Pull request merged**
