### PR TITLE
Mafia lock conduit-extra == 1.1.11

### PR DESCRIPTION
**Pull request by EduardSergeev**
To fix the build until conduit-extra is fixed

### CODE REVIEW

**Comment by nhibberd** [comment]
Need a 7.8.4 lock file as well

**Comment by nhibberd** [comment]
:+1: on :green_apple:

**Comment by domdere** [comment]
@nhibberd am i going to need the lock file for https://github.com/ambiata/princess/pull/51 as well?

**Comment by EduardSergeev** [comment]
> Need a 7.8.4 lock file as well

Do we actually need 7.8.3? I've just deleted it realising I am using legacy version

**Comment by tmcgilchrist** [comment]
I'm using 7.8.4 and 7.10.3 for what it's worth.

**Comment by EduardSergeev** [comment]
> I'm using 7.8.4 and 7.10.3 for what it's worth.

And I believe it is 7.10.2 in CI. I guess we need to agree on the policy: do we add .lock files for all possible versions or only CI versions? `lock-7.8.*` would be useful here :wink: 
/cc @jystic

**Comment by tmcgilchrist** [comment]
New version was released last night with my fixes. http://hackage.haskell.org/package/conduit-extra-1.1.12.1 @EduardSergeev @domdere

**Comment by domdere** [comment]
@tmcgilchrist cool thanks :D

**Pull request merged**
