### PR TITLE
Remove x-either.

### PR DESCRIPTION
**Pull request by markhibberd**
@amosr @jystic @charleso @nhibberd

### CODE REVIEW

**Comment by jystic** [comment]
👍

**Comment by olorin** [comment]
:+1:, just curious about the reasoning behind `ExceptT` over `EitherT` in the first place?

**Comment by jystic** [comment]
@olorin mtl style type class instances are usually implemented for all the `transformers` transformers, but not for `either`

**Comment by olorin** [comment]
> @olorin mtl style type class instances are usually implemented for all the transformers transformers, but not for either

Ah right, makes sense. :+1:

**Comment by jystic** [comment]
A few examples of this are [MonadAWS](http://hackage.haskell.org/package/amazonka-1.3.6/docs/Network-AWS.html#t:MonadAWS), [MFunctor](http://hackage.haskell.org/package/mmorph-1.0.6/docs/Control-Monad-Morph.html#t:MFunctor), [MonadResource](http://hackage.haskell.org/package/resourcet-1.1.7.5/docs/Control-Monad-Trans-Resource.html#t:MonadResource)

**Comment by markhibberd** [comment]
@olorin will try to dig up original issue, quick version is:they are basically identical for all intent - just one has a crap name, the problem with the old EitherT is that it is largely unused now, and most things we depend on use ExceptT (it also has missing instances - which Ed is happy to add most of the time) but there is no compelling reason for EitherT, and is largely swimming upstream.

**Comment by markhibberd** [comment]
Yeh @jystic beat me to it, better examples.

ExceptT isn't without its problems, it has silly "bugs" in the form of unused/unnecessary constraints that EitherT didn't suffer from, but we have been able to work around that for most cases.

**Comment by nhibberd** [comment]
:100:

**Comment by markhibberd** [comment]
@olorin https://github.com/ambiata/yak/issues/73

**Comment by amosr** [comment]
thanks! 🐗

**Comment by olorin** [comment]
Thanks @markhibberd, makes sense.

**Comment by charleso** [comment]
👍

**Pull request merged**
