### PR TITLE
Extend lens upper bounds

### PR DESCRIPTION
**Pull request by charleso**
! @thumphries @jystic 

We're hoping to use a more recent version of containers to get `Map.Merge`.

```
--- Diff for | 4.14 → 4.15.1 | ---
- Data.Map.Lens
· Control.Lens.Internal.Zoom
[+ Added] [- Removed] [× Modified] [· Unmodified]
```
/jury approved @jystic @nhibberd

### CODE REVIEW

**Comment by jystic** [comment]
👍 

not sure if you're using mismi, but that will have the same issue I think

**Comment by charleso** [comment]
> not sure if you're using mismi, but that will have the same issue I think

Yeah not using mismi, so I'm not worried in this case

**Comment by nhibberd** [comment]
:+1:

**Comment by thumphries** [comment]
👍

**Pull request merged**
