### PR TITLE
Lock to lifted-base-0.2.3.6 for GHC 7.8.4

### PR DESCRIPTION
**Pull request by jystic**
/cc @charleso

### CODE REVIEW

**Comment by jystic** [comment]
In the meantime I've files an issue upstream, we should probably send them a patch, but I'm not yet sure why they did s/Trustworthy/Safe in the first place. /cc @erikd-ambiata

**Comment by charleso** [comment]
Thanks @jystic

**Comment by charleso** [comment]
👍

**Comment by charleso** [comment]
Is this going to break in anything downstream that's using 7.8?

**Pull request merged**
