### PR TITLE
Add hushM combinator

### PR DESCRIPTION
**Pull request by jystic**
/cc @tranma

### CODE REVIEW

**Comment by tranma** [comment]
```Haskell
-- Hush all synchronous exceptions
hushAll = hushM (constTrue)
```
nice :+1:

**Comment by jystic** [comment]
```hs
constTrue :: SomeException -> Bool
constTrue e =
  isNothing (fromException e :: Maybe ArithException) &&
  isNothing (fromException e :: Maybe ArrayException) &&
  isNothing (fromException e :: Maybe AssertionFailed) &&
  isNothing (fromException e :: Maybe AsyncException) &&
  isNothing (fromException e :: Maybe BlockedIndefinitelyOnMVar) &&
  isNothing (fromException e :: Maybe BlockedIndefinitelyOnSTM) &&
  isNothing (fromException e :: Maybe Deadlock) &&
  isNothing (fromException e :: Maybe Dynamic) &&
  isNothing (fromException e :: Maybe ErrorCall) &&
  isNothing (fromException e :: Maybe ExitCode) &&
  isNothing (fromException e :: Maybe NestedAtomically) &&
  isNothing (fromException e :: Maybe NoMethodError) &&
  isNothing (fromException e :: Maybe NonTermination) &&
  isNothing (fromException e :: Maybe PatternMatchFail) &&
  isNothing (fromException e :: Maybe RecConError) &&
  isNothing (fromException e :: Maybe RecSelError) &&
  isNothing (fromException e :: Maybe RecUpdError)
```
? :D

**Comment by tranma** [comment]
haha, don't think we can catch `AsyncException` though

**Comment by jystic** [comment]
These are the ones that are not caught by `syncIO`

**Pull request merged**
